### ISSUE TITLE
the theme is not available

### ISSUE THREAD

**Issue by sakutepov** [elliotwaite/jetbrains-cyberpunk-theme#3] opened 2022-05-31 06:47 UTC
After update to 1.0.11 the theme has stopped being available
![Снимок экрана 2022-05-31 в 09 47 02](https://user-images.githubusercontent.com/44964230/171109666-477dd80b-930b-46af-96bd-0a17f1b21ce9.png)
![Снимок экрана 2022-05-31 в 09 47 22](https://user-images.githubusercontent.com/44964230/171109720-ac1fd3a4-85cf-4aa9-8952-ef45f0117c30.png)

**Comment by elliotwaite** [comment] 2022-05-31 06:55
🤨 Strange. Thanks for reporting this. I will investigate.

**Comment by elliotwaite** [comment] 2022-05-31 07:04
I just tested reinstalling it and at first, I experienced the same thing, it didn't show up in the "Theme" dropdown menu, but then I restarted the IDE and that fixed it. Can you try restarting your IDE to see if that resolves the issue?

I'm not sure why a restart would be required. I don't think that step was required in the past.

If that doesn't resolve the issue, can you let me know which IDE you are using, and the version of that IDE?

**Comment by sakutepov** [comment] 2022-05-31 08:18
it helps with DataGrip, but PyCharm and GoLang didn't work

**Comment by sakutepov** [comment] 2022-05-31 08:23
it took more than one restart to solve
did it until it appeared here
![Снимок экрана 2022-05-31 в 11 23 39](https://user-images.githubusercontent.com/44964230/171127643-42d74145-b353-404a-ba0d-304867e209db.png)

**Comment by elliotwaite** [comment] 2022-05-31 20:01
Okay. I tested reinstalling it again on my computer and I actually didn't even have to restart the IDE, I just had to close and reopen the settings window, so I might not be experiencing the same issue you are.

If the restarts resolved the issue for you, I think this issue might be due to something in the IDE code and not the latest theme update. The latest theme update was supposed to only change a single color, so unless I accidentally changed something else, I don't think this update introduced this issue, but I can't be sure.

I'm not sure if this is related, but someone opened this issue on YouTrack 2 months ago and labeled it as a regression: [IDEA requires restart after installing new theme plugin](https://youtrack.jetbrains.com/issue/IDEA-291686).

Do you think I should close this issue for now and assume it's an issue with the IDE?

**Comment by sakutepov** [comment] 2022-06-01 07:43
the theme is working and it really looks like an IDE bug

**Closed as completed** 2022-06-01 07:42 UTC

**Comment by elliotwaite** [comment] 2022-06-01 07:54
Okay, sounds good.
